ChoacuryOS Kernel: /mnt/g/source/Projects/TeamChoacury/kernel/src/drivers/utils/utils.c File Reference
utils.c File Reference
#include "utils.h"
#include <stdint.h>
Functions
void * memcpy (void *dst, const void *src, size_t len)
Copy memory from source to destination.
void * memmove (void *dst, const void *src, size_t len)
Moves memory from source to destination.
void * memset (void *dst, int val, size_t len)
Sets a value in memory.
int memcmp (const void *a, const void *b, size_t len)
Compares 2 pointers in memory.
void iota (int n, char str[])
Converts an integer to string?
atoi_result_t atoi (const char *str)
Attempts to convert a string to an integer.
int abs (int x)
Gets the absolute (positive) value of the integer.
int strlen (const char *str)
Gets the length of the string.
int strcmp (const char *str1, const char *str2)
Compares 2 strings.
char * strcpy (char *dest, const char *src)
Copies a string from source to destination.
char * strcat (char *dest, const char *src)
Concatenates (adds to the end) a string.
int tolower (int ch)
Converts an upper character to a lower character.
int toupper (int ch)
Converts a lower character to an upper character.
int get_num_length (uint64_t num)
void uint64_to_string (uint64_t number, char *buffer)
float sin(float x);
Function Documentation
abs()
int abs (int x)
Gets the absolute (positive) value of the integer.
Parameters
x The original number
Returns
The absolute (positive) number
Definition at line 85 of file utils.c.
               {
    return x < 0 ? -x : x;
}
atoi()
atoi_result_t atoi (const char * str)
Attempts to convert a string to an integer.
Parameters
The string to attempt to convert
Returns
Returns an atoi_result_t object with a valid boolean, and an integer
Definition at line 59 of file utils.c.
{
    // parse optional sign
    bool negative = (*str == '-');
    if (*str == '-' || *str == '+') {
        str++;
    }
    // parse digits
    int value = 0;
    while (*str) {
        if (*str < '0' || *str > '9') {
            atoi_result_t result = { .valid = false, .value = 0 };
            return result;
        }
        value = (value * 10) + (*str - '0');
        str++;
    }
    if (negative) {
        value = -value;
    }
    atoi_result_t result = { .valid = true, .value = value };
    return result;
}
References atoi_result_t::valid.
get_num_length()
int get_num_length (uint64_t num)
Definition at line 175 of file utils.c.
{
    int length = 0;
    do {
        length++;
        num /= 10;
    } while (num > 0);
    return length;
}
Referenced by uint64_to_string().
iota()
void iota (int n, char str[])
Converts an integer to string?
Parameters
n
str
Todo:
Write better docs for this function
Definition at line 47 of file utils.c.
{
    int i, sign;
    if ((sign = n) < 0) n = -n;
    i = 0;
    do {
        str[i++] = n % 10 + '0';
    } while ((n /= 10) > 0);
    if (sign < 0) str[i++] = '-';
    str[i] = '\0';
}
memcmp()
int memcmp (const void * a, const void * b, size_t len)
Compares 2 pointers in memory.
Parameters
a The first pointer
b The second pointer
len The length of the data
Returns
a_u8[i] - b_u8[i] or 0
Todo:
Add a better explanation for the return type
Definition at line 36 of file utils.c.
{
    const u8* a_u8 = (const u8*)a;
    const u8* b_u8 = (const u8*)b;
    for (size_t i = 0; i < len; i++) {
        if (a_u8[i] != b_u8[i]) {
            return (int)a_u8[i] - (int)b_u8[i];
        }
    }
    return 0;
}
References len.
memcpy()
void * memcpy (void * dest, const void * source, size_t nbytes)
Copy memory from source to destination.
Parameters
dest The destination pointer
source The source pointer
nbytes The length of the source in bytes
Returns
The destination pointer
Definition at line 4 of file utils.c.
{
    u8* dst_u8 = (u8*)dst;
    const u8* src_u8 = (const u8*)src;
    for (size_t i = 0; i < len; i++) {
        dst_u8[i] = src_u8[i];
    }
    return dst;
}
References len.
memmove()
void * memmove (void * dest, const void * source, size_t nbytes)
Moves memory from source to destination.
Parameters
dest The destination pointer
source The source pointer
nbytes The length of the source in bytes
Returns
The destination pointer
Definition at line 13 of file utils.c.
{
    u8* dst_u8 = (u8*)dst;
    const u8* src_u8 = (const u8*)src;
    if (dst_u8 < src_u8) {
        for (size_t i = 0; i < len; i++) {
            dst_u8[i] = src_u8[i];
        }
    } else {
        for (u32 i = 1; i <= len; i++) {
            dst_u8[len - i] = src_u8[len - i];
        }
    }
    return dst;
}
References len.
memset()
void * memset (void * dest, int val, size_t len)
Sets a value in memory.
Parameters
dest The destination pointer
val The value to set the memory to
len The length of the destination
Returns
The destination pointer
Definition at line 28 of file utils.c.
{
    u8* dst_u8 = (u8*)dst;
    for (size_t i = 0; i < len; i++) {
        dst_u8[i] = val;
    }
    return dst;
}
References len.
strcat()
char * strcat (char * dest, const char * src)
Concatenates (adds to the end) a string.
Parameters
dest The destination pointer
src The source pointer (The string to add)
Returns
The destination pointer
Definition at line 149 of file utils.c.
{
    int len = strlen(dest);
    int i = 0;
    while (src[i]) {
        dest[len + i] = src[i];
        i++;
    }
    dest[len + i] = '\0';
    return dest;
}
References len, and strlen().
strcmp()
int strcmp (const char * str1, const char * str2)
Compares 2 strings.
Parameters
str1 The first string pointer
str2 The second string poitner
Returns
*str1 - *str2
Definition at line 131 of file utils.c.
{
    while (*str1 && *str2 && *str1 == *str2) {
        str1++;
        str2++;
    }
    return *str1 - *str2;
}
strcpy()
char * strcpy (char * dest, const char * src)
Copies a string from source to destination.
Parameters
dest The destination pointer
src The source pointer
Returns
The destination pointer
Definition at line 139 of file utils.c.
{
    int i = 0;
    while (src[i]) {
        dest[i] = src[i];
        i++;
    }
    dest[i] = '\0';
    return dest;
}
strlen()
int strlen (const char * str)
Gets the length of the string.
Parameters
str The string
Returns
The length of the string
Definition at line 123 of file utils.c.
{
    int i = 0;
    while (str[i]) {
        i++;
    }
    return i;
}
Referenced by strcat(), and terminal_writestring().
tolower()
int tolower (int ch)
Converts an upper character to a lower character.
Parameters
ch The upper character
Returns
The lower character (Or the original if it was already lower case)
Definition at line 160 of file utils.c.
                    {
    if (ch < 'A' || ch > 'Z') {
        return ch;
    }
    return ch - 'A' + 'a';
}
toupper()
int toupper (int ch)
Converts a lower character to an upper character.
Parameters
ch The lower character
Returns
The higher character (Or the original if it was already higher case)
Definition at line 167 of file utils.c.
                    {
    if (ch < 'a' || ch > 'z') {
        return ch;
    }
    return ch - 'a' + 'A';
}
uint64_to_string()
void uint64_to_string (uint64_t number, char * buffer)
float sin(float x);
Converts an unsigned 64-bit integer to a string
Parameters
number The number
buffer The string pointer
Definition at line 184 of file utils.c.
{
    int length = get_num_length(number);
    buffer[length] = '\0';
    int index = length - 1;
    do {
        buffer[index--] = '0' + (number % 10);
        number /= 10;
    } while (number > 0);
}
References get_num_length().