ChoacuryOS Kernel: /mnt/g/source/Projects/TeamChoacury/kernel/src/kernel.c File Reference
kernel.c File Reference
#include <stdint.h>
#include <stddef.h>
#include "multiboot.h"
Macros
#define VGA_WIDTH 80
#define VGA_HEIGHT 25
#define VGA_MEMORY 0xB8000
Functions
size_t strlen (const char *str)
void terminal_initialize (void)
void terminal_writestring (const char *data, size_t row, size_t col)
void kernel_main (multiboot_info_t *mbd, uint32_t magic)
Macro Definition Documentation
VGA_HEIGHT
#define VGA_HEIGHT 25
Definition at line 7 of file kernel.c.
VGA_MEMORY
#define VGA_MEMORY 0xB8000
Definition at line 8 of file kernel.c.
VGA_WIDTH
#define VGA_WIDTH 80
Definition at line 6 of file kernel.c.
Function Documentation
kernel_main()
void kernel_main (multiboot_info_t * mbd, uint32_t magic)
Bug:
Bootloader not providing multiboot information
Definition at line 40 of file kernel.c.
{
    terminal_initialize();
    terminal_writestring("1234567890",0,0);
    /// @bug Bootloader not providing multiboot information
    if(magic != MULTIBOOT_BOOTLOADER_MAGIC) {
        //terminal_writestring("Kernel Panic: Bootloader did not provide multiboot information", 0, 0);
        //asm volatile("hlt");
    }
    while (1) {}
}
References MULTIBOOT_BOOTLOADER_MAGIC, terminal_initialize(), and terminal_writestring().
strlen()
size_t strlen (const char * str)
Definition at line 10 of file kernel.c.
{
    size_t len = 0;
    while (str[len])
        len++;
    return len;
}
References len.
Referenced by terminal_writestring().
terminal_initialize()
void terminal_initialize (void)
Definition at line 17 of file kernel.c.
{
    volatile uint16_t* buffer = (volatile uint16_t*) VGA_MEMORY;
    for (size_t y = 0; y < VGA_HEIGHT; y++) {
        for (size_t x = 0; x < VGA_WIDTH; x++) {
            const size_t index = y * VGA_WIDTH + x;
            buffer[index] = (uint16_t) ' ' | (uint16_t) (15 | 0 << 4) << 8;
        }
    }
}
References VGA_HEIGHT, VGA_MEMORY, and VGA_WIDTH.
Referenced by kernel_main().
terminal_writestring()
void terminal_writestring (const char * data, size_t row, size_t col)
Definition at line 28 of file kernel.c.
{
    volatile uint16_t* buffer = (volatile uint16_t*) VGA_MEMORY;
    size_t len = strlen(data);
    for (size_t i = 0; i < len; i++) {
        const size_t t = row * VGA_WIDTH + (col + i);
        if (t < VGA_WIDTH * VGA_HEIGHT) {
            buffer[t] = (uint16_t) data[i] | (uint16_t) (15 | 0 << 4) << 8;
        }
    }
}
References len, strlen(), VGA_HEIGHT, VGA_MEMORY, and VGA_WIDTH.
Referenced by kernel_main().